# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YrBPRUnOGKVq5oNrJbcjk7XKA_oaAXK
"""

!pip install imbalanced-learn xgboost boruta shap lime

# ============================================================
# LEAKAGE-FREE NESTED CROSS-VALIDATION
# Diabetes Classification with:
#   - Class-weight balanced XGBoost
#   - Multiple imbalance strategies
#   - 10 classifiers
#   - 7 feature-ranking methods
#   - Greedy XGBoost feature selection
#   - 5-fold outer CV x 10 repeats = 50 outer test folds
#   - 5-fold inner CV for classifier/model selection
#   - Outer-test folds are NEVER used for model selection
#
# IMPORTANT:
#   Resampling, scaling, feature ranking, feature selection, and
#   classifier selection are performed using training data only.
#   The outer test fold is used ONCE for final evaluation.
# ============================================================

# If needed, run once in a separate cell:
# !pip install -U pandas numpy matplotlib seaborn scipy scikit-learn imbalanced-learn xgboost boruta shap lime

import os
import math
import warnings
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import wilcoxon

from imblearn.over_sampling import ADASYN
from imblearn.under_sampling import TomekLinks

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.base import clone

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
)
from sklearn.feature_selection import mutual_info_classif
from sklearn.inspection import permutation_importance

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
)

from xgboost import XGBClassifier
from boruta import BorutaPy
import shap
from lime.lime_tabular import LimeTabularExplainer


# ============================================================
# 0. SETTINGS
# ============================================================

DATA_FILE = "data.csv"

RANDOM_SEEDS = [
    42, 101, 2024, 777, 999,
    123, 456, 789, 1357, 2468
]

N_OUTER_SPLITS = 5
N_OUTER_REPEATS = 10
N_INNER_SPLITS = 5

TOP_K = 6
RANDOM_STATE = 42

# The original code effectively used the final strategy from the
# strategy loop for Parts 2-4. Keep that behavior explicitly.
RANKING_STRATEGY = "ADASYN+TomekLinks"

warnings.filterwarnings("ignore")


# ============================================================
# 1. LOAD & CLEAN DATA
# ============================================================

df = pd.read_csv(DATA_FILE).dropna().reset_index(drop=True)

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip().str.lower()

binary_map = {
    "gender": {"male": 1, "female": 0},
    "family_diabetes": {"yes": 1, "no": 0},
    "hypertensive": {"yes": 1, "no": 0},
    "family_hypertension": {"yes": 1, "no": 0},
    "cardiovascular_disease": {"yes": 1, "no": 0},
    "stroke": {"yes": 1, "no": 0},
    "diabetic": {"yes": 1, "no": 0},
}

df.replace(binary_map, inplace=True)

X = df.drop(columns=["diabetic"]).copy()
y = df["diabetic"].copy()

# Ensure predictors are numeric after the same encoding used above.
non_numeric = X.select_dtypes(exclude=np.number).columns.tolist()
if non_numeric:
    raise ValueError(
        "Non-numeric predictor columns remain after encoding: "
        f"{non_numeric}"
    )

if y.isna().any():
    raise ValueError("Target contains NaN values after cleaning.")

if X.isna().any().any():
    raise ValueError("Predictors contain NaN values after cleaning.")

y = y.astype(int)

print("Dataset shape:", X.shape)
print("Class distribution:")
print(y.value_counts())


# ============================================================
# 2. CLASSIFIERS
# ============================================================

def make_xgb(y_train):
    """
    Class-weight balanced XGBoost.

    scale_pos_weight is calculated ONLY from the training data
    supplied to this function. Therefore, no outer-test information
    enters the class-weight calculation.
    """
    counts = pd.Series(y_train).value_counts()
    neg = counts.get(0, 0)
    pos = counts.get(1, 0)

    if pos == 0:
        raise ValueError("Training fold contains no positive samples.")

    scale_pos_weight = float(neg / pos)

    return XGBClassifier(
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        scale_pos_weight=scale_pos_weight,
        n_jobs=-1,
    )


def make_models(y_train):
    """
    Create fresh estimators for every training fold.
    """
    return {
        "LogisticRegression": LogisticRegression(
            max_iter=1000,
            class_weight="balanced",
            random_state=RANDOM_STATE,
        ),
        "SVM": SVC(
            kernel="rbf",
            probability=True,
            class_weight="balanced",
            random_state=RANDOM_STATE,
        ),
        "KNN": KNeighborsClassifier(),
        "DecisionTree": DecisionTreeClassifier(
            class_weight="balanced",
            random_state=RANDOM_STATE,
        ),
        "NaiveBayes": GaussianNB(),
        "RandomForest": RandomForestClassifier(
            n_estimators=200,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1,
        ),
        "ExtraTrees": ExtraTreesClassifier(
            n_estimators=200,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1,
        ),
        "GradientBoosting": GradientBoostingClassifier(
            random_state=RANDOM_STATE
        ),
        "AdaBoost": AdaBoostClassifier(
            random_state=RANDOM_STATE
        ),
        "XGBoost": make_xgb(y_train),
    }


# ============================================================
# 3. IMBALANCE STRATEGIES
# ============================================================

def apply_strategy(X_train, y_train, strategy):
    """
    Resampling is performed ONLY on the current training fold.

    No validation/test data are passed to ADASYN or TomekLinks.
    """
    if strategy == "Original":
        return X_train.copy(), y_train.copy()

    if strategy == "ADASYN":
        sampler = ADASYN(random_state=RANDOM_STATE)
        return sampler.fit_resample(X_train, y_train)

    if strategy == "TomekLinks":
        sampler = TomekLinks()
        return sampler.fit_resample(X_train, y_train)

    if strategy == "ADASYN+TomekLinks":
        X_tmp, y_tmp = ADASYN(
            random_state=RANDOM_STATE
        ).fit_resample(X_train, y_train)

        return TomekLinks().fit_resample(X_tmp, y_tmp)

    raise ValueError(f"Unknown strategy: {strategy}")


strategies = [
    "Original",
    "ADASYN",
    "TomekLinks",
    "ADASYN+TomekLinks",
]


# ============================================================
# 4. METRIC HELPERS
# ============================================================

def safe_metric(metric_function, y_true, y_pred):
    return metric_function(
        y_true,
        y_pred,
        zero_division=0,
    )


def evaluate_predictions(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": safe_metric(precision_score, y_true, y_pred),
        "Recall": safe_metric(recall_score, y_true, y_pred),
        "F1": safe_metric(f1_score, y_true, y_pred),
        "CM": confusion_matrix(y_true, y_pred),
    }


# ============================================================
# 5. INNER-CV CLASSIFIER SELECTION
# ============================================================

def inner_classifier_selection(X_train, y_train, strategy, seed):
    """
    Select the classifier using ONLY inner-CV performance.

    The outer-test fold is not available here.

    For each inner split:
      1. Split the outer-training data.
      2. Apply resampling only to inner-training data.
      3. Fit scaling only to inner-training data.
      4. Fit classifier on inner-training data.
      5. Evaluate on untouched inner-validation data.

    Selection criterion = mean inner-CV F1.
    """

    inner_cv = StratifiedKFold(
        n_splits=N_INNER_SPLITS,
        shuffle=True,
        random_state=seed,
    )

    scores = {
        name: []
        for name in make_models(y_train).keys()
    }

    for inner_train_idx, inner_val_idx in inner_cv.split(X_train, y_train):

        X_inner_train = X_train.iloc[inner_train_idx].copy()
        y_inner_train = y_train.iloc[inner_train_idx].copy()

        X_inner_val = X_train.iloc[inner_val_idx].copy()
        y_inner_val = y_train.iloc[inner_val_idx].copy()

        # Resampling ONLY inside inner-training data.
        X_res, y_res = apply_strategy(
            X_inner_train,
            y_inner_train,
            strategy,
        )

        # Scaling ONLY fitted on inner-training data.
        scaler = StandardScaler()
        X_res_scaled = pd.DataFrame(
            scaler.fit_transform(X_res),
            columns=X_res.columns,
            index=X_res.index,
        )

        X_val_scaled = pd.DataFrame(
            scaler.transform(X_inner_val),
            columns=X_inner_val.columns,
            index=X_inner_val.index,
        )

        for name, model in make_models(y_inner_train).items():

            model.fit(X_res_scaled, y_res)
            y_pred = model.predict(X_val_scaled)

            scores[name].append(
                f1_score(
                    y_inner_val,
                    y_pred,
                    zero_division=0,
                )
            )

    mean_scores = {
        name: float(np.mean(values))
        for name, values in scores.items()
    }

    selected_classifier = max(
        mean_scores,
        key=mean_scores.get,
    )

    return selected_classifier, mean_scores


# ============================================================
# 6. OUTER-CV CLASSIFIER SELECTION + FINAL EVALUATION
# ============================================================

outer_classifier_results = []
outer_predictions = {}
outer_confusions = {}

for repeat_no, seed in enumerate(RANDOM_SEEDS, start=1):

    outer_cv = StratifiedKFold(
        n_splits=N_OUTER_SPLITS,
        shuffle=True,
        random_state=seed,
    )

    for fold_no, (outer_train_idx, outer_test_idx) in enumerate(
        outer_cv.split(X, y),
        start=1,
    ):

        X_outer_train = X.iloc[outer_train_idx].copy()
        y_outer_train = y.iloc[outer_train_idx].copy()

        X_outer_test = X.iloc[outer_test_idx].copy()
        y_outer_test = y.iloc[outer_test_idx].copy()

        for strategy in strategies:

            # ------------------------------------------------
            # CLASSIFIER SELECTION:
            # INNER CV ONLY
            # ------------------------------------------------
            selected_classifier, inner_scores = (
                inner_classifier_selection(
                    X_outer_train,
                    y_outer_train,
                    strategy,
                    seed,
                )
            )

            # ------------------------------------------------
            # FINAL FIT:
            # Use ALL outer-training data only.
            # The outer test fold remains untouched.
            # ------------------------------------------------
            X_res, y_res = apply_strategy(
                X_outer_train,
                y_outer_train,
                strategy,
            )

            scaler = StandardScaler()
            X_res_scaled = pd.DataFrame(
                scaler.fit_transform(X_res),
                columns=X_res.columns,
            )

            X_test_scaled = pd.DataFrame(
                scaler.transform(X_outer_test),
                columns=X_outer_test.columns,
                index=X_outer_test.index,
            )

            if selected_classifier == "XGBoost":
                final_model = make_xgb(y_outer_train)
            else:
                final_model = make_models(
                    y_outer_train
                )[selected_classifier]

            final_model.fit(X_res_scaled, y_res)

            # ------------------------------------------------
            # OUTER TEST:
            # Used ONLY here, after all selections are finished.
            # ------------------------------------------------
            y_test_pred = final_model.predict(X_test_scaled)

            metrics = evaluate_predictions(
                y_outer_test,
                y_test_pred,
            )

            record = {
                "Repeat": repeat_no,
                "Seed": seed,
                "OuterFold": fold_no,
                "Strategy": strategy,
                "SelectedClassifier": selected_classifier,
                "Accuracy": metrics["Accuracy"],
                "Precision": metrics["Precision"],
                "Recall": metrics["Recall"],
                "F1": metrics["F1"],
            }

            # Store the complete inner-CV scores for transparency.
            for clf_name, score in inner_scores.items():
                record[f"InnerF1_{clf_name}"] = score

            outer_classifier_results.append(record)

            key = (
                repeat_no,
                fold_no,
                strategy,
            )

            outer_predictions[key] = (
                y_outer_test.to_numpy(),
                y_test_pred,
            )

            outer_confusions[key] = metrics["CM"]

            print(
                f"Repeat {repeat_no:02d}/10 | "
                f"Fold {fold_no}/5 | "
                f"{strategy:20s} | "
                f"Selected: {selected_classifier:18s} | "
                f"Outer F1: {metrics['F1']:.4f}"
            )


outer_classifier_df = pd.DataFrame(
    outer_classifier_results
)

outer_classifier_df.to_csv(
    "nested_outer_classifier_results.csv",
    index=False,
)

print("\n============================================================")
print("NESTED CV CLASSIFIER SELECTION SUMMARY")
print("============================================================")

classifier_summary = (
    outer_classifier_df
    .groupby(["Strategy", "SelectedClassifier"])
    .agg(
        Count=("F1", "size"),
        Mean_F1=("F1", "mean"),
        Std_F1=("F1", "std"),
        Mean_Accuracy=("Accuracy", "mean"),
        Mean_Precision=("Precision", "mean"),
        Mean_Recall=("Recall", "mean"),
    )
    .sort_values(
        ["Strategy", "Mean_F1"],
        ascending=[True, False],
    )
)

print(classifier_summary)

classifier_summary.to_csv(
    "nested_classifier_selection_summary.csv"
)


# ============================================================
# 7. XGBOOST PERFORMANCE ACROSS IMBALANCE STRATEGIES
#
# This section evaluates XGBoost specifically using the same
# leakage-free outer-fold design.
# ============================================================

xgb_outer_records = []

for repeat_no, seed in enumerate(RANDOM_SEEDS, start=1):

    outer_cv = StratifiedKFold(
        n_splits=N_OUTER_SPLITS,
        shuffle=True,
        random_state=seed,
    )

    for fold_no, (
        outer_train_idx,
        outer_test_idx,
    ) in enumerate(
        outer_cv.split(X, y),
        start=1,
    ):

        X_outer_train = X.iloc[outer_train_idx].copy()
        y_outer_train = y.iloc[outer_train_idx].copy()

        X_outer_test = X.iloc[outer_test_idx].copy()
        y_outer_test = y.iloc[outer_test_idx].copy()

        for strategy in strategies:

            X_res, y_res = apply_strategy(
                X_outer_train,
                y_outer_train,
                strategy,
            )

            scaler = StandardScaler()

            X_res_scaled = pd.DataFrame(
                scaler.fit_transform(X_res),
                columns=X_res.columns,
            )

            X_test_scaled = pd.DataFrame(
                scaler.transform(X_outer_test),
                columns=X_outer_test.columns,
            )

            xgb = make_xgb(y_outer_train)

            xgb.fit(
                X_res_scaled,
                y_res,
            )

            y_pred = xgb.predict(
                X_test_scaled
            )

            metrics = evaluate_predictions(
                y_outer_test,
                y_pred,
            )

            xgb_outer_records.append(
                {
                    "Repeat": repeat_no,
                    "Seed": seed,
                    "OuterFold": fold_no,
                    "Strategy": strategy,
                    "Accuracy": metrics["Accuracy"],
                    "Precision": metrics["Precision"],
                    "Recall": metrics["Recall"],
                    "F1": metrics["F1"],
                }
            )


xgb_outer_df = pd.DataFrame(
    xgb_outer_records
)

xgb_outer_df.to_csv(
    "xgb_nested_outer_results.csv",
    index=False,
)

xgb_summary = (
    xgb_outer_df
    .groupby("Strategy")
    .agg(
        Accuracy_Mean=("Accuracy", "mean"),
        Accuracy_SD=("Accuracy", "std"),
        Precision_Mean=("Precision", "mean"),
        Precision_SD=("Precision", "std"),
        Recall_Mean=("Recall", "mean"),
        Recall_SD=("Recall", "std"),
        F1_Mean=("F1", "mean"),
        F1_SD=("F1", "std"),
    )
)

print("\nXGBoost nested outer-test summary:")
print(xgb_summary)

xgb_summary.to_csv(
    "xgb_nested_outer_summary.csv"
)


# ============================================================
# 8. XGBOOST METRIC COMPARISON FIGURE
# ============================================================

plt.figure(figsize=(10, 6))

plot_df = xgb_summary[
    [
        "Accuracy_Mean",
        "Precision_Mean",
        "Recall_Mean",
        "F1_Mean",
    ]
].copy()

plot_df.plot(
    kind="bar",
    figsize=(10, 6),
)

plt.title(
    "Class-Weight Balanced XGBoost Performance "
    "Across Imbalance Strategies"
)
plt.ylabel("Mean Outer-Test Score")
plt.ylim(0, 1)
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(
    "xgboost_nested_comparison_metrics.png",
    dpi=300,
)
plt.show()


# ============================================================
# 9. FEATURE RANKING FUNCTIONS
#
# IMPORTANT:
# These functions are called ONLY with outer-training data.
# Therefore, the outer test fold cannot influence feature ranking.
# ============================================================

def calculate_feature_rankings(
    X_train,
    y_train,
    strategy,
    seed=42,
):

    # Resampling only the supplied training data.
    X_res, y_res = apply_strategy(
        X_train,
        y_train,
        strategy,
    )

    # Scaling only the supplied training data.
    scaler = StandardScaler()

    X_res = pd.DataFrame(
        scaler.fit_transform(X_res),
        columns=X_res.columns,
    )

    # --------------------------------------------------------
    # Mutual Information
    # --------------------------------------------------------
    mi_scores = mutual_info_classif(
        X_res,
        y_res,
        random_state=seed,
    )

    mi_rank = (
        pd.Series(
            mi_scores,
            index=X_res.columns,
        )
        .sort_values(ascending=False)
    )

    mi_rank.to_csv(
        "rank_mutual_info_outer_training.csv"
    )

    # --------------------------------------------------------
    # Correlation
    # --------------------------------------------------------
    corr_rank = (
        abs(
            pd.concat(
                [
                    X_res,
                    y_res.rename("diabetic"),
                ],
                axis=1,
            )
            .corr()["diabetic"]
        )
        .drop("diabetic")
        .sort_values(ascending=False)
    )

    corr_rank.to_csv(
        "rank_correlation_outer_training.csv"
    )

    # --------------------------------------------------------
    # Random Forest Importance
    # --------------------------------------------------------
    rf = RandomForestClassifier(
        n_estimators=500,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1,
    )

    rf.fit(
        X_res,
        y_res,
    )

    rf_rank = (
        pd.Series(
            rf.feature_importances_,
            index=X_res.columns,
        )
        .sort_values(ascending=False)
    )

    rf_rank.to_csv(
        "rank_random_forest_outer_training.csv"
    )

    # --------------------------------------------------------
    # Boruta
    # --------------------------------------------------------
    rfc = RandomForestClassifier(
        n_estimators=200,
        n_jobs=-1,
        class_weight="balanced",
        max_depth=6,
        random_state=seed,
    )

    boruta = BorutaPy(
        rfc,
        n_estimators="auto",
        random_state=seed,
    )

    boruta.fit(
        X_res.values,
        y_res.values,
    )

    boruta_rank = (
        pd.Series(
            boruta.ranking_,
            index=X_res.columns,
        )
        .sort_values()
    )

    boruta_rank.to_csv(
        "rank_boruta_outer_training.csv"
    )

    # --------------------------------------------------------
    # SHAP
    # --------------------------------------------------------
    background = shap.kmeans(
        X_res,
        min(10, len(X_res)),
    )

    shap_explainer = shap.KernelExplainer(
        rf.predict_proba,
        background,
    )

    sample_n = min(200, len(X_res))

    shap_values = shap_explainer.shap_values(
        X_res.iloc[:sample_n],
        nsamples=100,
    )

    if isinstance(shap_values, list):
        shap_class1 = shap_values[1]
    else:
        shap_values = np.asarray(shap_values)

        if shap_values.ndim == 3:
            shap_class1 = shap_values[:, :, 1]
        else:
            shap_class1 = shap_values

    shap_importance = np.abs(
        shap_class1
    ).mean(axis=0)

    shap_rank = (
        pd.Series(
            shap_importance,
            index=X_res.columns,
        )
        .sort_values(ascending=False)
    )

    shap_rank.to_csv(
        "rank_shap_outer_training.csv"
    )

    # --------------------------------------------------------
    # LIME
    # --------------------------------------------------------
    lime_explainer = LimeTabularExplainer(
        X_res.values,
        feature_names=X_res.columns.tolist(),
        class_names=[
            "non-diabetic",
            "diabetic",
        ],
        discretize_continuous=True,
        random_state=seed,
    )

    importance = np.zeros(
        X_res.shape[1]
    )

    for i in range(
        min(100, len(X_res))
    ):

        exp = lime_explainer.explain_instance(
            X_res.iloc[i].values,
            rf.predict_proba,
            num_features=X_res.shape[1],
        )

        for feat, val in exp.as_list():

            for f in X_res.columns:

                if f in feat:
                    importance[
                        X_res.columns.get_loc(f)
                    ] += abs(val)
                    break

    lime_rank = (
        pd.Series(
            importance,
            index=X_res.columns,
        )
        .sort_values(ascending=False)
    )

    lime_rank.to_csv(
        "rank_lime_outer_training.csv"
    )

    # --------------------------------------------------------
    # PDI
    # --------------------------------------------------------
    rf_pdi = RandomForestClassifier(
        n_estimators=500,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1,
    )

    rf_pdi.fit(
        X_res,
        y_res,
    )

    pdi_result = permutation_importance(
        rf_pdi,
        X_res,
        y_res,
        n_repeats=20,
        random_state=seed,
        scoring="accuracy",
        n_jobs=-1,
    )

    pdi_rank = (
        pd.Series(
            pdi_result.importances_mean,
            index=X_res.columns,
        )
        .sort_values(ascending=False)
    )

    pdi_rank.to_csv(
        "rank_pdi_outer_training.csv"
    )

    return {
        "MutualInfo": mi_rank,
        "Correlation": corr_rank,
        "RandomForest": rf_rank,
        "SHAP": shap_rank,
        "LIME": lime_rank,
        "PDI": pdi_rank,
        "Boruta": boruta_rank,
    }, X_res, y_res


# ============================================================
# 10. FEATURE-RANKING + GREEDY XGBOOST SELECTION
#
# This is performed separately inside every outer training fold.
# The outer test fold is NEVER supplied to this procedure.
# ============================================================

def greedy_xgb_selection(
    ranking_methods,
    X_res,
    y_res,
    seed=42,
):

    # --------------------------------------------------------
    # Top-6 extraction
    # --------------------------------------------------------
    top_features = {
        name: ranking.index[:TOP_K].tolist()
        for name, ranking
        in ranking_methods.items()
    }

    # --------------------------------------------------------
    # Histogram of Top-6 features
    # --------------------------------------------------------
    feature_counter = Counter()

    for feats in top_features.values():
        feature_counter.update(feats)

    hist_df = (
        pd.DataFrame.from_dict(
            feature_counter,
            orient="index",
            columns=["Frequency"],
        )
        .sort_values(
            by="Frequency",
            ascending=False,
        )
    )

    # --------------------------------------------------------
    # Global ranked feature list
    # --------------------------------------------------------
    rank_positions = {}

    for ranking in ranking_methods.values():

        for rank, feat in enumerate(
            ranking.index[:TOP_K],
            start=1,
        ):
            rank_positions.setdefault(
                feat,
                [],
            ).append(rank)

    ranked_features = pd.DataFrame(
        {
            "Frequency": hist_df["Frequency"],
            "MeanRank": {
                f: np.mean(rank_positions[f])
                for f in hist_df.index
            },
        }
    ).sort_values(
        by=["Frequency", "MeanRank"],
        ascending=[False, True],
    )

    global_feature_list = (
        ranked_features.index.tolist()
    )

    # --------------------------------------------------------
    # Greedy XGBoost
    # --------------------------------------------------------
    selected_features = []
    best_f1 = 0.0
    f1_progress = []

    greedy_cv = StratifiedKFold(
        n_splits=N_INNER_SPLITS,
        shuffle=True,
        random_state=seed,
    )

    for feat in global_feature_list:

        candidate = (
            selected_features + [feat]
        )

        X_sub = X_res[candidate]

        f1_scores = []

        for train_idx, test_idx in greedy_cv.split(
            X_sub,
            y_res,
        ):

            X_train_g = X_sub.iloc[train_idx]
            y_train_g = y_res.iloc[train_idx]

            X_test_g = X_sub.iloc[test_idx]
            y_test_g = y_res.iloc[test_idx]

            model = Pipeline(
                [
                    (
                        "scaler",
                        StandardScaler(),
                    ),
                    (
                        "xgb",
                        make_xgb(y_train_g),
                    ),
                ]
            )

            model.fit(
                X_train_g,
                y_train_g,
            )

            pred = model.predict(
                X_test_g
            )

            f1_scores.append(
                f1_score(
                    y_test_g,
                    pred,
                    zero_division=0,
                )
            )

        mean_f1 = float(
            np.mean(f1_scores)
        )

        if (
            len(selected_features) == 0
            or mean_f1 >= best_f1
        ):
            selected_features.append(feat)
            best_f1 = mean_f1
            f1_progress.append(mean_f1)

    # --------------------------------------------------------
    # Ablation feature sets
    # --------------------------------------------------------
    top1_union = list(
        set(
            r[0]
            for r in top_features.values()
        )
    )

    top3_union = list(
        set(
            f
            for r in top_features.values()
            for f in r[:3]
        )
    )

    top5_union = list(
        set(
            f
            for r in top_features.values()
            for f in r[:5]
        )
    )

    top3_intersection = list(
        set.intersection(
            *(
                set(r[:3])
                for r in top_features.values()
            )
        )
    )

    feature_sets = {
        "Proposed": top3_union,
        "Top-1 Union": top1_union,
        "Top-3 Union": selected_features,
        "Top-5 Union": top5_union,
        "Top-3 Intersection": top3_intersection,
    }

    feature_sets = {
        k: v
        for k, v
        in feature_sets.items()
        if len(v) > 0
    }

    return (
        top_features,
        ranked_features,
        selected_features,
        feature_sets,
        f1_progress,
    )


# ============================================================
# 11. OUTER-TEST EVALUATION OF FEATURE SETS
#
# Feature rankings and feature-set construction are done using
# outer-training data only.
#
# Feature-set comparison/selection uses inner CV.
# The final chosen feature set is then evaluated ONCE on outer test.
# ============================================================

def evaluate_feature_set_inner(
    X_train,
    y_train,
    features,
    strategy,
    seed,
):

    inner_cv = StratifiedKFold(
        n_splits=N_INNER_SPLITS,
        shuffle=True,
        random_state=seed,
    )

    scores = []

    for train_idx, val_idx in inner_cv.split(
        X_train,
        y_train,
    ):

        X_it = X_train.iloc[train_idx][features]
        y_it = y_train.iloc[train_idx]

        X_iv = X_train.iloc[val_idx][features]
        y_iv = y_train.iloc[val_idx]

        X_res, y_res = apply_strategy(
            X_it,
            y_it,
            strategy,
        )

        model = Pipeline(
            [
                (
                    "scaler",
                    StandardScaler(),
                ),
                (
                    "xgb",
                    make_xgb(y_it),
                ),
            ]
        )

        model.fit(
            X_res,
            y_res,
        )

        pred = model.predict(
            X_iv
        )

        scores.append(
            f1_score(
                y_iv,
                pred,
                zero_division=0,
            )
        )

    return float(
        np.mean(scores)
    )


def run_feature_nested_evaluation():

    records = []
    selected_feature_records = []

    for repeat_no, seed in enumerate(
        RANDOM_SEEDS,
        start=1,
    ):

        outer_cv = StratifiedKFold(
            n_splits=N_OUTER_SPLITS,
            shuffle=True,
            random_state=seed,
        )

        for fold_no, (
            outer_train_idx,
            outer_test_idx,
        ) in enumerate(
            outer_cv.split(X, y),
            start=1,
        ):

            X_outer_train = X.iloc[
                outer_train_idx
            ].copy()

            y_outer_train = y.iloc[
                outer_train_idx
            ].copy()

            X_outer_test = X.iloc[
                outer_test_idx
            ].copy()

            y_outer_test = y.iloc[
                outer_test_idx
            ].copy()

            # ------------------------------------------------
            # Feature ranking ONLY on outer training data.
            # ------------------------------------------------
            rankings, X_res_rank, y_res_rank = (
                calculate_feature_rankings(
                    X_outer_train,
                    y_outer_train,
                    RANKING_STRATEGY,
                    seed,
                )
            )

            (
                top_features,
                ranked_features,
                greedy_features,
                feature_sets,
                f1_progress,
            ) = greedy_xgb_selection(
                rankings,
                X_res_rank,
                y_res_rank,
                seed,
            )

            # ------------------------------------------------
            # Select the final feature set by INNER CV only.
            # ------------------------------------------------
            inner_feature_scores = {}

            for name, features in feature_sets.items():

                inner_feature_scores[name] = (
                    evaluate_feature_set_inner(
                        X_outer_train,
                        y_outer_train,
                        features,
                        RANKING_STRATEGY,
                        seed,
                    )
                )

            selected_feature_set_name = max(
                inner_feature_scores,
                key=inner_feature_scores.get,
            )

            selected_features = feature_sets[
                selected_feature_set_name
            ]

            # Save the feature-selection information.
            selected_feature_records.append(
                {
                    "Repeat": repeat_no,
                    "Seed": seed,
                    "OuterFold": fold_no,
                    "Strategy": RANKING_STRATEGY,
                    "SelectedFeatureSet":
                        selected_feature_set_name,
                    "SelectedFeatures":
                        "|".join(selected_features),
                    **{
                        f"InnerF1_{k}": v
                        for k, v
                        in inner_feature_scores.items()
                    },
                }
            )

            # ------------------------------------------------
            # Final outer-training fit.
            # ------------------------------------------------
            X_ot = X_outer_train[
                selected_features
            ]

            X_oe = X_outer_test[
                selected_features
            ]

            X_res_final, y_res_final = (
                apply_strategy(
                    X_ot,
                    y_outer_train,
                    RANKING_STRATEGY,
                )
            )

            final_model = Pipeline(
                [
                    (
                        "scaler",
                        StandardScaler(),
                    ),
                    (
                        "xgb",
                        make_xgb(
                            y_outer_train
                        ),
                    ),
                ]
            )

            final_model.fit(
                X_res_final,
                y_res_final,
            )

            # ------------------------------------------------
            # OUTER TEST: final unbiased evaluation.
            # ------------------------------------------------
            y_pred = final_model.predict(
                X_oe
            )

            metrics = evaluate_predictions(
                y_outer_test,
                y_pred,
            )

            records.append(
                {
                    "Repeat": repeat_no,
                    "Seed": seed,
                    "OuterFold": fold_no,
                    "Strategy": RANKING_STRATEGY,
                    "SelectedFeatureSet":
                        selected_feature_set_name,
                    "NFeatures":
                        len(selected_features),
                    "Accuracy":
                        metrics["Accuracy"],
                    "Precision":
                        metrics["Precision"],
                    "Recall":
                        metrics["Recall"],
                    "F1":
                        metrics["F1"],
                }
            )

            print(
                f"[Feature nested CV] "
                f"Repeat {repeat_no:02d}/10 | "
                f"Fold {fold_no}/5 | "
                f"Selected set: "
                f"{selected_feature_set_name:18s} | "
                f"Features: {len(selected_features):2d} | "
                f"Outer F1: {metrics['F1']:.4f}"
            )

    return (
        pd.DataFrame(records),
        pd.DataFrame(selected_feature_records),
    )


feature_outer_df, selected_feature_df = (
    run_feature_nested_evaluation()
)

feature_outer_df.to_csv(
    "feature_selection_nested_outer_results.csv",
    index=False,
)

selected_feature_df.to_csv(
    "feature_selection_nested_inner_results.csv",
    index=False,
)


# ============================================================
# 12. FEATURE-SET SUMMARY
# ============================================================

feature_summary = (
    feature_outer_df
    .groupby("SelectedFeatureSet")
    .agg(
        N=("F1", "size"),
        Accuracy_Mean=("Accuracy", "mean"),
        Accuracy_SD=("Accuracy", "std"),
        Precision_Mean=("Precision", "mean"),
        Precision_SD=("Precision", "std"),
        Recall_Mean=("Recall", "mean"),
        Recall_SD=("Recall", "std"),
        F1_Mean=("F1", "mean"),
        F1_SD=("F1", "std"),
        NFeatures_Mean=("NFeatures", "mean"),
    )
    .sort_values(
        "F1_Mean",
        ascending=False,
    )
)

print("\n============================================================")
print("FEATURE-SELECTION NESTED OUTER-TEST SUMMARY")
print("============================================================")
print(feature_summary)

feature_summary.to_csv(
    "feature_selection_nested_outer_summary.csv"
)


# ============================================================
# 13. FEATURE FREQUENCY FROM THE OUTER-TRAINING RANKINGS
#
# This is descriptive only. It does not use outer-test samples.
# ============================================================

# Reconstruct a final descriptive ranking on the full dataset's
# training information only if desired. To avoid introducing
# leakage into the reported outer-test estimates, this section
# is deliberately NOT used for model selection or evaluation.


# ============================================================
# 14. WILCOXON TESTS
#
# Compare repeated outer-test F1 values.
#
# IMPORTANT:
# These tests are descriptive comparisons of the 50 outer-test
# evaluations. They are NOT used to select the final model.
# ============================================================

def wilcoxon_against_reference(
    results_df,
    metric="F1",
    reference_name="Proposed",
):

    pivot = results_df.pivot_table(
        index=["Repeat", "OuterFold"],
        columns="SelectedFeatureSet",
        values=metric,
    )

    if reference_name not in pivot.columns:
        print(
            f"Reference '{reference_name}' "
            "not available."
        )
        return

    reference = pivot[
        reference_name
    ].dropna()

    output = []

    for name in pivot.columns:

        if name == reference_name:
            continue

        current = pivot[
            name
        ].dropna()

        common = reference.index.intersection(
            current.index
        )

        if len(common) < 2:
            continue

        a = reference.loc[common]
        b = current.loc[common]

        try:
            stat, p = wilcoxon(
                a,
                b,
                zero_method="wilcox",
                alternative="two-sided",
            )
        except ValueError:
            stat, p = np.nan, np.nan

        output.append(
            {
                "Reference": reference_name,
                "Compared": name,
                "N": len(common),
                "WilcoxonStatistic": stat,
                "PValue": p,
            }
        )

    return pd.DataFrame(output)


wilcoxon_results = wilcoxon_against_reference(
    feature_outer_df,
    metric="F1",
    reference_name="Proposed",
)

if wilcoxon_results is not None:
    print(
        "\nWilcoxon results "
        "(descriptive; NOT used for model selection):"
    )
    print(wilcoxon_results)

    wilcoxon_results.to_csv(
        "wilcoxon_feature_sets_outer_results.csv",
        index=False,
    )


# ============================================================
# 15. FINAL REPRODUCIBILITY INFORMATION
# ============================================================

print("\n============================================================")
print("LEAKAGE-FREE NESTED CV COMPLETE")
print("============================================================")

print(f"Outer folds per repeat : {N_OUTER_SPLITS}")
print(f"Outer repeats          : {N_OUTER_REPEATS}")
print(
    f"Total outer test folds : "
    f"{N_OUTER_SPLITS * N_OUTER_REPEATS}"
)
print(f"Inner folds             : {N_INNER_SPLITS}")
print(f"Seeds                   : {RANDOM_SEEDS}")

print("\nKey leakage controls:")
print("1. Outer test folds are never used for classifier selection.")
print("2. Classifier selection uses inner CV only.")
print("3. Resampling is fitted only on training partitions.")
print("4. StandardScaler is fitted only on training partitions.")
print("5. XGBoost scale_pos_weight is computed from training labels only.")
print("6. Feature ranking is performed using outer-training data only.")
print("7. Feature-set selection is performed using inner CV only.")
print("8. The outer test fold is used only for final evaluation.")
print("9. The reported outer-test results contain 50 evaluations.")